<<<<<<< HEAD
/***** [ 테이블 ] *****/

CREATE TABLE CUSTOMER(

CUSTOMER_NO NUMBER PRIMARY KEY,

CUSTOMER_NAME VARCHAR2(60) NOT NULL,

CUSTOMER_TEL VARCHAR2(30) NOT NULL,

CUSTOMER_ADDRESS VARCHAR2(200) NOT NULL

);

/***** [ 시퀀스 ] *****/

CREATE SEQUENCE SEQ_CUSTOMER_NO NOCACHE;


SELECT *
FROM CUSTOMER



=======
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_KHJ IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO kh_khj;

ALTER USER 
>>>>>>> d7fa541603f069fa6bc4c7056d784bf59ebb2ca8
